name: Build and Publish Release

on:
  release:
    types:
      - created

jobs:
  pre:
    runs-on: windows-latest
    steps:
    - name: Dump GitHub context
      env:
        GITHUB_CONTEXT: ${{ toJson(github) }}
      run: echo "$GITHUB_CONTEXT"
  build:
    runs-on: windows-latest
    if: github.ref == 'refs/heads/master' || (startsWith(github.ref, 'refs/tags/') && contains(github.ref,'-alpha'))
    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0
    - name: Fetch all history for all tags and branches
      run: |
        git fetch --prune

    - name: Setup MSBuild.exe
      uses: warrenbuckley/Setup-MSBuild@v1

    - name: MSBuild
      working-directory: src
      run: |
        dotnet restore --disable-parallel
        # can't use pure dotnet build because NET35 compile doesn't work
        msbuild XAMLMarkupExtensions.csproj -verbosity:minimal /p:Configuration=Release 
        #/property:NugetAPIKey=${{ secrets.NugetAPIKey }}
